export const UPDATE_GEOGRAPHICAL_ELIGIBILITY_FILTERS =
  "UPDATE_GEOGRAPHICAL_ELIGIBILITY_FILTERS";
export const UPDATE_GEOGRAPHICAL_ELIGIBILITY_BY_TYPE =
  "UPDATE_GEOGRAPHICAL_ELIGIBILITY_BY_TYPE";
export const UPDATE_ELIGIBILITY_FILTERS = "UPDATE_ELIGIBILITY_FILTERS";
export const UPDATE_SERVED_FILTERS = "UPDATE_SERVED_FILTERS";
export const UPDATE_GEOGRAPHICAL_SERVED_FILTERS =
  "UPDATE_GEOGRAPHICAL_SERVED_FILTERS";
export const UPDATE_GEOGRAPHICAL_SERVED_BY_TYPE =
  "UPDATE_GEOGRAPHICAL_SERVED_BY_TYPE";
