export const CREATE_GEOGRAPHICAL_ELIGIBILITY_FILTERS =
  "CREATE_GEOGRAPHICAL_ELIGIBILITY_FILTERS";
export const UPDATE_GEOGRAPHICAL_ELIGIBILITY_FILTERS =
  "UPDATE_GEOGRAPHICAL_ELIGIBILITY_FILTERS";
export const UPDATE_GEOGRAPHICAL_ELIGIBILITY_BY_TYPE =
  "UPDATE_GEOGRAPHICAL_ELIGIBILITY_BY_TYPE";
