export const UPDATE_PROGRAM_FILTERS = "UPDATE_PROGRAM_FILTERS";
export const UPDATE_BY_TYPE = "UPDATE_BY_TYPE";
export const UPDATE_FILTER_TYPE = "UPDATE_FILTER_TYPE";
export const UPDATE_OTHER_FILTERS = "UPDATE_OTHER_FILTERS";
